Revert "trying to work around div0 undefined reference to raise stuff on arm"
This reverts commit 32d4cff78fc8f433d426a9c3cacfa72b12b8c3a9.

well that didn't work